services:
  server:
    build:
      context: .
      target: final
    env_file:
      - .env
    ports:
      - 8080:8080
    deploy:
      resources:
        # Simulate 1 vCPU
        limits:
          cpus: '0.5'
          memory: 256M
